ENALBE_APT_UPDATE: false
ENALBE_UPDATE_ALL_PKG: false
ENABLE_INSTALL_PKG: true
ENABLE_UNINSTALL_PKG: false

CONTAINERD_RELEASE_VERSION: 1.7.1
RUNC_RELEASE_VERSION: 1.1.7

CNI:
  CONF:
    DIR: /etc/containerd
  BIN:
    CONTAINERD: /opt/containerd/{{ CONTAINERD_RELEASE_VERSION }}
    RUNC: /opt/runc/{{ RUNC_RELEASE_VERSION }}/bin
